<?php 
echo "<a href=\"#\"><i class=\"fa fa-sitemap\"></i> Multi-Level Dropdown<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-second-level\">";
echo "<li>";
echo "<a href=\"php/ripartizione_geografica.php?cod_rip=ITALIA CENTRALE\">ITALIA CENTRALE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">TOSCANA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Massa-Carrara</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Lucca</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Pistoia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Firenze</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Livorno</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Pisa</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Arezzo</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Siena</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Grosseto</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Prato</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">UMBRIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Perugia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Terni</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">MARCHE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Pesaro Urbino</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Ancona</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Macerata</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Ascoli Piceno</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">FERMO</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">LAZIO<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Viterbo</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Rieti</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Roma</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Latina</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Frosinone</a>";
echo "</li>";
echo "</ul>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "<a href=\"php/ripartizione_geografica.php?cod_rip=ITALIA INSULARE\">ITALIA INSULARE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">SICILIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Trapani</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Palermo</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Messina</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Agrigento</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Caltanissetta</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Enna</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Catania</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Ragusa</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Siracusa</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">SARDEGNA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Sassari</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Nuoro</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Cagliari</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Oristano</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Olbia-Tempio</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Ogliastra</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Medio Campidano</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Carbonia-Iglesias</a>";
echo "</li>";
echo "</ul>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "<a href=\"php/ripartizione_geografica.php?cod_rip=ITALIA MERIDIONALE\">ITALIA MERIDIONALE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">ABRUZZO<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">L'Aquila</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Teramo</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Pescara</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Chieti</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">MOLISE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Campobasso</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Isernia</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">CAMPANIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Caserta</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Benevento</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Napoli</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Avellino</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Salerno</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">PUGLIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Foggia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Bari</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Taranto</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Brindisi</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Lecce</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Barletta Andria e Trani</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">BASILICATA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Potenza</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Matera</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">CALABRIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Cosenza</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Catanzaro</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Reggio di Calabria</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Crotone</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Vibo Valentia</a>";
echo "</li>";
echo "</ul>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "<a href=\"php/ripartizione_geografica.php?cod_rip=ITALIA NORD-OCCIDENTALE\">ITALIA NORD-OCCIDENTALE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">PIEMONTE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Torino</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Vercelli</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Novara</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Cuneo</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Asti</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Alessandria</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Biella</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Verbano-Cusio-Ossola</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">VALLE D'AOSTA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Valle d'Aosta</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">LOMBARDIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Varese</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Como</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Sondrio</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Milano</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Bergamo</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Brescia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Pavia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Cremona</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Mantova</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Lecco</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Lodi</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">MONZA - BRIANZA</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">LIGURIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Imperia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Savona</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Genova</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">La Spezia</a>";
echo "</li>";
echo "</ul>";
echo "</ul>";
echo "</li>";
echo "<li>";
echo "<a href=\"php/ripartizione_geografica.php?cod_rip=ITALIA NORD-ORIENTALE\">ITALIA NORD-ORIENTALE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">TRENTINO-ALTO ADIGE<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Bolzano - Bozen</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Trento</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">VENETO<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Verona</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Vicenza</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Belluno</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Treviso</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Venezia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Padova</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Rovigo</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">FRIULI-VENEZIA GIULIA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Udine</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Gorizia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Trieste</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Pordenone</a>";
echo "</li>";
echo "</ul>";
echo "<li>";
echo "<a href=\"#\">EMILIA-ROMAGNA<span class=\"fa arrow\"></span></a>";
echo "<ul class=\"nav nav-third-level\">";
echo "<li>";
echo "<a href=\"#\">Piacenza</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Parma</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Reggio nell'Emilia</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Modena</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Bologna</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Ferrara</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Ravenna</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Forli'-Cesena</a>";
echo "</li>";
echo "<li>";
echo "<a href=\"#\">Rimini</a>";
echo "</li>";
echo "</ul>";
echo "</ul>";
echo "</li>";
echo "</ul>";
?>